mkdir ../../lib
mkdir ../../lib/linux
mkdir ../../lib/linux/intel_mkl_mt

mkdir OpenSMOKE_AddOns
mkdir OpenSMOKE_AddOns/intel_mkl_mt
make -f OpenSMOKE_AddOns_INTEL_MKL_MT clean
make -f OpenSMOKE_AddOns_INTEL_MKL_MT

mkdir OpenSMOKE_Basic
mkdir OpenSMOKE_Basic/intel_mkl_mt
make -f OpenSMOKE_Basic_INTEL_MKL_MT clean
make -f OpenSMOKE_Basic_INTEL_MKL_MT

mkdir OpenSMOKE_BatchReactor
mkdir OpenSMOKE_BatchReactor/intel_mkl_mt
make -f OpenSMOKE_BatchReactor_INTEL_MKL_MT clean
make -f OpenSMOKE_BatchReactor_INTEL_MKL_MT

mkdir OpenSMOKE_CHEMKINInterpreter
mkdir OpenSMOKE_CHEMKINInterpreter/intel_mkl_mt
make -f OpenSMOKE_CHEMKINInterpreter_INTEL_MKL_MT clean
make -f OpenSMOKE_CHEMKINInterpreter_INTEL_MKL_MT

mkdir OpenSMOKE_Distributions
mkdir OpenSMOKE_Distributions/intel_mkl_mt
make -f OpenSMOKE_Distributions_INTEL_MKL_MT clean
make -f OpenSMOKE_Distributions_INTEL_MKL_MT

mkdir OpenSMOKE_Engine
mkdir OpenSMOKE_Engine/intel_mkl_mt
make -f OpenSMOKE_Engine_INTEL_MKL_MT clean
make -f OpenSMOKE_Engine_INTEL_MKL_MT

mkdir OpenSMOKE_Droplet
mkdir OpenSMOKE_Droplet/intel_mkl_mt
make -f OpenSMOKE_Droplet_INTEL_MKL_MT clean
make -f OpenSMOKE_Droplet_INTEL_MKL_MT

mkdir OpenSMOKE_Flame1D
mkdir OpenSMOKE_Flame1D/intel_mkl_mt
make -f OpenSMOKE_Flame1D_INTEL_MKL_MT clean
make -f OpenSMOKE_Flame1D_INTEL_MKL_MT
 
mkdir OpenSMOKE_Flamelet
mkdir OpenSMOKE_Flamelet/intel_mkl_mt
make -f OpenSMOKE_Flamelet_INTEL_MKL_MT clean
make -f OpenSMOKE_Flamelet_INTEL_MKL_MT

mkdir OpenSMOKE_KinPP
mkdir OpenSMOKE_KinPP/intel_mkl_mt
make -f OpenSMOKE_KinPP_INTEL_MKL_MT clean
make -f OpenSMOKE_KinPP_INTEL_MKL_MT

mkdir OpenSMOKE_IdealReactors
mkdir OpenSMOKE_IdealReactors/intel_mkl_mt
make -f OpenSMOKE_IdealReactors_INTEL_MKL_MT clean
make -f OpenSMOKE_IdealReactors_INTEL_MKL_MT

mkdir OpenSMOKE_Interfaces
mkdir OpenSMOKE_Interfaces/intel_mkl_mt
make -f OpenSMOKE_Interfaces_INTEL_MKL_MT clean
make -f OpenSMOKE_Interfaces_INTEL_MKL_MT

mkdir OpenSMOKE_MixManager
mkdir OpenSMOKE_MixManager/intel_mkl_mt
make -f OpenSMOKE_MixManager_INTEL_MKL_MT clean
make -f OpenSMOKE_MixManager_INTEL_MKL_MT

mkdir OpenSMOKE_PlugFlowReactor
mkdir OpenSMOKE_PlugFlowReactor/intel_mkl_mt
make -f OpenSMOKE_PlugFlowReactor_INTEL_MKL_MT clean
make -f OpenSMOKE_PlugFlowReactor_INTEL_MKL_MT

mkdir OpenSMOKE_CSTR
mkdir OpenSMOKE_CSTR/intel_mkl_mt
make -f OpenSMOKE_CSTR_INTEL_MKL_MT clean
make -f OpenSMOKE_CSTR_INTEL_MKL_MT

mkdir OpenSMOKE_PreProcessing
mkdir OpenSMOKE_PreProcessing/intel_mkl_mt
make -f OpenSMOKE_PreProcessing_INTEL_MKL_MT clean
make -f OpenSMOKE_PreProcessing_INTEL_MKL_MT

mkdir OpenSMOKE_QMOM
mkdir OpenSMOKE_QMOM/intel_mkl_mt
make -f OpenSMOKE_QMOM_INTEL_MKL_MT clean
make -f OpenSMOKE_QMOM_INTEL_MKL_MT

mkdir OpenSMOKE_ShockTube
mkdir OpenSMOKE_ShockTube/intel_mkl_mt
make -f OpenSMOKE_ShockTube_INTEL_MKL_MT clean
make -f OpenSMOKE_ShockTube_INTEL_MKL_MT

mkdir OpenSMOKE_LiquidProperties
mkdir OpenSMOKE_LiquidProperties/intel_mkl_mt
make -f OpenSMOKE_LiquidProperties_INTEL_MKL_MT clean
make -f OpenSMOKE_LiquidProperties_INTEL_MKL_MT

mkdir OpenSMOKE_ICEM
mkdir OpenSMOKE_ICEM/intel_mkl_mt
make -f OpenSMOKE_ICEM_INTEL_MKL_MT clean
make -f OpenSMOKE_ICEM_INTEL_MKL_MT

mkdir OpenSMOKE_SurfaceChemistry
mkdir OpenSMOKE_SurfaceChemistry/intel_mkl_mt
make -f OpenSMOKE_SurfaceChemistry_INTEL_MKL_MT clean
make -f OpenSMOKE_SurfaceChemistry_INTEL_MKL_MT

mkdir OpenSMOKE_SymbolicKinetics
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/sandiego_avio
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_nc7_avio
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_h2conox_nothermal_1101
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_h2conox_nonnh_1101
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_h2conox_non2o_1101
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_h2conox_1101
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_c1c3htnox_avio_0702
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/polimi_c1c3htnox_1101
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/gri30
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/gri12
mkdir OpenSMOKE_SymbolicKinetics/intel_mkl_mt/fluent_drm22_polimi_nox
make -f OpenSMOKE_SymbolicKinetics_INTEL_MKL_MT clean
make -f OpenSMOKE_SymbolicKinetics_INTEL_MKL_MT

